### PR TITLE
99 footer

### PR DESCRIPTION
**Pull request by ralphZero**
- [x] Footer rebuilt
- [x] responsiveness

### CODE REVIEW

**Comment by andresmgomez** [comment]
Good job in adding markup for footer, but only tablet screens adjust. Try to make it responsive.

**Comment by jonathans199** [comment]
Hi @ralphZero all looks well on desktop but on mobile looks weird, when you get a chance pls review, thx

Screen Shot 2022-09-25 at 6 30 02 PM

**Review by jonathans199 — APPROVED** [review]
Looks great, thank you

**Comment by jonathans199** [comment]
Looks great, awesome job 💪

**Pull request merged**
