### PR TITLE
  updated Restaurant addNewForm with Image uploading directly to fire…

### PR DESCRIPTION
**Pull request by jonathans199**
- Added Server Side Rendering for Restaurants
- Now pulling restaurants from firestore directly no API
- Add new restaurant with image now working directly into Firebase Storage then into Firestore

### CODE REVIEW

**Review by andresmgomez — COMMENTED** [review]
@Mrmckney did we talked on previous PRs, to not have inline styles?

**Comment by jonathans199** [comment]
> @Mrmckney did we talked on previous PRs, to not have inline styles?
yes for sure @andresmgomez, where do you see the inline styles?  Also I didn't change any styling only functional, let me know thanks

**Comment by Mrmckney** [comment]
@jonathans199 @andresmgomez 
Yes trying to keep in-line styling to a minimum but in some cases I allow only one property to be inlined but any more than that should become a class.

**Review by andresmgomez — CHANGES_REQUESTED** [review]
Yes, we can stick to that rule. So these styles have to be put in a class name.

Screen Shot 2022-08-19 at 10 08 07 AM

**Review by stolomeo — APPROVED** [review]

**Comment by jonathans199** [comment]
@andresmgomez - nice catch

so currently are not using that `imageUploader` component just yet, so lets push forward for this PR while I work on refactoring that `imageUploader` utility component.

**Pull request merged**
